config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => { :omniauth_callbacks => 'omniauth_callbacks' }
  match "products/:product_id/reviews" => "reviews#create", via: [:post,:get]
  resources :products do
    resources :reviews
  end
  
  root 'products#index'

end

app/models/product.rb
class Product < ActiveRecord::Base
 has_many :reviews
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :set_product, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!, :except => [:index ]
  #skip_before_filter :authenticate_user!, :only => [:index]
  #before_filter :require_login, :except => {:index }

  def index
    @products = Product.all
  end

  def show
  end

  def new
    @product = Product.new
  end

  def edit
  end
  
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def set_product
      @product = Product.find(params[:id])
    end

    def product_params
      params.require(:product).permit(:name, :price, :description)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_product.html.erb
<div>
  <h2><%= product.name %></h2>
  <h4><%= number_to_currency product.price %></h4>
  <p><%= product.description %></p>
  <% if current_page? product %>
    <p><%= link_to "Back to Products", products_path %></p>
  <% else %>
    <p><%= link_to "Read Comments", product %></p>
  <% end %>
  <div class="clear"></div>
</div>

app/views/products/edit.html.erb
<h1>Editing Product</h1>
<%= form_for @product do |f| %>
  <div>
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div>
    <%= f.label :price %>
    <%= f.text_field :price %>
  </div>
	<div>
    <%= f.label :Decription %>
    <%= f.text_area :description %>
  </div>

  <div>
    <%= f.submit %>
    <%= link_to 'Show', @product %> |
		<%= link_to 'Back', product_path %>
  </div>
<% end %>

app/views/products/index.html.erb
<%= link_to 'New Product', new_product_path %>
<h1>Products</h1>

<%= render @products %>

app/views/products/new.html.erb
<h1>New Product</h1>
<%= form_for @product do |f| %>
  <div>
    <%= f.label :name %>
    <div>
      <%= f.text_field :name %>
    </div>
  </div>
  <div>
    <%= f.label :price %>
    <div>
      <%= f.text_field :price %>
    </div>
  </div>
  <div>
    <%= f.label :Description %>
    <div>
      <%= f.text_area :description %>
    </div>
  </div>

  <div>
    <%= f.submit %>
    <%= link_to 'Cancel', products_path%>
  </div>
<% end %>

app/views/products/show.html.erb
<div id="movie">
  <%= render @product %>
</div>
<div class="fb-comments" data-href="http://rubyeffect.com" data-numposts="5" data-colorscheme="light"></div>
<div id="reviews">
  <h2><%= pluralize @product.reviews.size, "Comments" %></h2>

  <% @product.reviews.each do |review| %>
    <div class="review">
      <div class="content"><%= review.content %></div>
      <em>
        &mdash;
        <%= review.name %> gave it
        <strong><%= pluralize review.rating, "star" %></strong>
      </em>
    </div>
  <% end %>

  <h4>Write a review</h4>
  <%= form_for [@product, Review.new] do |f| %>
    <div class="field">
      <%= f.label :rating %>
      <%= f.select :rating, 1..5 %>
    </div>
    <div class="field">
      <%= f.label :name, "Your name" %>
      <%= f.text_field :name %>
    </div>
    <div class="field">
      <%= f.text_area :content, rows: 5, cols: 40 %>
    </div>
    <div class="actions"><%= f.submit %></div>
  <% end %>
</div>